#!/usr/bin/env node
/**
 * 將 Logo SVG 轉為 PNG，供 PWA / Apple Touch Icon 使用
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const svgPath = join(root, "src", "assets", "logo.svg");
const outPath = join(root, "src", "generated", "icons.ts");

const sharp = (await import("sharp")).default;
const svg = readFileSync(svgPath);

const sizes = [
  { size: 180, name: "icon180" },
  { size: 192, name: "icon192" },
  { size: 512, name: "icon512" },
];

const results = {};
for (const { size, name } of sizes) {
  const png = await sharp(svg)
    .resize(size, size)
    .png()
    .toBuffer();
  results[name] = png.toString("base64");
}

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `/** Auto-generated by scripts/build-icons.mjs - do not edit */
export const icon180Base64 = "${results.icon180}";
export const icon192Base64 = "${results.icon192}";
export const icon512Base64 = "${results.icon512}";
`,
  "utf-8"
);
console.log("Built PNG icons -> src/generated/icons.ts");
