#!/usr/bin/env node
/**
 * 將 Tailwind 建置後的 CSS 嵌入為 TypeScript 模組，供 Worker 使用
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const cssPath = join(root, "dist", "styles.css");
const outPath = join(root, "src", "generated", "tailwind-css.ts");

const css = readFileSync(cssPath, "utf-8");
const escaped = css.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `/** Auto-generated by scripts/embed-css.mjs - do not edit */\nexport const tailwindStyles = \`${escaped}\`;\n`,
  "utf-8"
);
console.log("Embedded Tailwind CSS to src/generated/tailwind-css.ts");
